<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<%@ include file="/taglibs.jsp"%>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
    <title>Submit an assignment</title>
  </head>
  <body>
    <div class="breadcrumbs">
      <strong>You are here:</strong>
      <a href="index.jsp">OpenMentor</a> >> 
      <a href="selectAssignment.html">Submit an Assignment</a> >>
      View Analysis
    </div>
    <div class="textheading">
      View analysis results
    </div>
    <p>
      In this page, you can explore the comment analysis generated by
      Open Mentor.
    </p>
    <c:set var="table" value="${model.analysis}"/>
    <c:set var="rowCount" value="0"/>
    <c:set var="limit" value="${model.commentlimit}"/>
    <c:if test="${requestScope.full}">
      <c:set var="limit" value="100"/>
    </c:if>
    <table style="commentTable">
      <thead>
        <tr class="topHeader">
          <th style="width: 9%">Category</th>
          <th style="width: 6%">${table.columnLabels[0]}</th>
          <th style="width: 6%">${table.columnLabels[1]}</th>
          <th style="width: 79%">${table.columnLabels[2]}</th>
        </tr>
      </thead>
      
      <tbody>
        <c:forEach var="row" items="${table.data}">
          <tr class="${((rowCount % 2) == 0) ? 'OffWhiteBG' : 'WhiteBG'}" valign="top">
            <td>
              <p>
                <em><c:out value="${table.rowLabels[rowCount]}"/></em>
              </p>
            </td>
            <c:set var="rowCount" value="${rowCount + 1}"/>
            <td class="number"><p>${row[0]}</p></td>
            <td class="number"><p>${row[1]}</p></td>
            <td>
              <c:set var="count" value="1"/>
              <c:forEach var="comment" items="${row[2]}">
                <p><!-- next line sytactically should be &lt; -->
                <c:if test="${count <= limit}">${comment}</c:if>
                </p>
                <c:set var="count" value="${count + 1}"/>
              </c:forEach>
              <c:if test="${count > (limit + 1)}">
                <p><i>...(and ${count - limit - 1} more)</i></p>
              </c:if>
            </td>
          </tr>
        </c:forEach>
      </tbody>
    </table>
  </body>
</html>
