<html>
  <head>
    <title>Site Index</title>
  </head>
  <body>
    <div class="breadcrumbs">
      <strong>You are here:</strong> 
      <a href="index.jsp">OpenMentor</a> >> Site Index
    </div>
    <div class="textheading">Site index</div>
    <h3>Select course</h3>
      <dl>
        <dt><a href="selectCourse.html">Choose a course</a></dt>
        <dd>You can use Open Mentor to do a number of different 
                analyses on the feedback for a particular course.
                To do this, you first need to choose a course to
                work with.
      </dl>
    <h3>Upload assignment</h3>
      <dl>
        <dt><a href="selectAssignment.html">Choose a file</a></dt>
        <dd>You can add as many files as you like to Open Mentor,
                marking each one with a grade, and assigning it
                to a particular student and a particular tutor. 
                After you have done this, this submission will
                form part of all later reports generated by
                Open Mentor. 
      </dl>
    <h3>View reports</h3>
      <dl>
        <dt><a href="listReports.html?type=course">Comment analysis for the course</a></dt>
        <dd>All the assignments for this course will be analysed. The
                report provides feedback by analysing the comments
                in terms of four major groupings and informs the
                user whether enough comments have been placed in
                each of these groups.</dd>
        <dt><a href="listReports.html?type=tutor">Comment analysis for tutors</a></dt>
        <dd>The assignments for tutors will be analysed. The
                report provides feedback by analysing the comments
                in terms of four major groupings and informs the
                user whether enough comments have been placed in
                each of these groups.</dd>
        <dt><a href="listReports.html?type=student">Comment analysis for students</a></dt>
        <dd>The assignments for students will be analysed. The
                report provides feedback by analysing the comments
                in terms of four major groupings and informs the
                user whether enough comments have been placed in
                each of these groups.</dd>
      </dl>
    <h3><a href="help.jsp">Help</a></h3>
    <h3><a href="signin.jsp">Sign out</a></h3>
  </body>
</html>
